### ISSUE TITLE
Fails to import on Win 10, version 7.6.6

### ISSUE THREAD

**Issue by frackham** [brianmaher84/PlantUML_Notepad-_UDL#3]
Fails to import on Win 10, version 7.6.6

Tried both manually, and via import (and after removing the userdefinelang.xml too).

Not sure if you're still maintaining this, completely understand if not ! :)

**Comment by brianmaher84** [comment]
Sorry for the late response.  I've tested on Win 10 7.6.6 locally and it imported successfully for me.

Then I couldn't select it in the main drop down for some reason.

Renaming it using the Notepad ++ GUI made it appear and it started working so maybe it is a bug in the Notepad ++ language importer.

**Comment by frackham** [comment]
Thank for the response - when you say rename it, do you mean in the filesystem or through the UI?

**Comment by brianmaher84** [comment]
Through the UI.

**Comment by frackham** [comment]
OK, thanks, will retry when I'm back at keyboard :)
